### PR TITLE
Dependency update & replacing autoprefixer

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Hey there,
since I'm learning lots of stuff from reviewing your code, I thought there might be something I could do to give back, so I made some simple updates (two Gems, one Bower package), but would also like to suggest replacing grunt-autoprefixer since it's been [deprecated](https://github.com/nDmitry/grunt-autoprefixer) in favor of [grunt-postcss](https://github.com/nDmitry/grunt-postcss), which takes a more modular approach and utilizes the autoprefixer-core package. I'd like to contribute more to your repo, but that's it for now,

take care,
S1SYPHOS

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
Also added quick normalize update, just for fun ...

**Comment by davidensinger** [comment]
I will take a look this weekend :)

**Comment by S1SYPHOS** [comment]
Great :+1:

**Comment by davidensinger** [comment]
Looks good. Merged and thanks!

I probably need to update my website more often :)

**Pull request merged**
